### ISSUE TITLE
Run JRE and J2CL tests from same class

### ISSUE THREAD

**Issue by cjgriscom** [mP1/j2cl-maven-plugin#381]
I have been integrating this plugin into one of my projects and so far it has been incredibly useful.  I've ported my JUnit tests to use the custom annotation package, using the structure in j2cl-java-io as an example.  The tests run well in the HTML runner, but now they aren't detected by the surefire plugin.  How would you recommend executing the tests on both targets without making a copy of the class?

I expect to make some contributions to this plugin and related packages as I get more familiar with them.  Thanks for your work so far.

**Comment by mP1** [comment]
> I've ported my JUnit tests to use the custom annotation package, using the structure in j2cl-java-io as an example

I think `JavaIoTestJ2cl` only actually works in surefire it doesnt get translated etc, the `@J2clTestInput(JavaIoTestJ2cl.class)` is a mistake/misleading.

> The tests run well in the HTML runner, but now they aren't detected by the surefire plugin. How would you recommend executing the tests on both targets without making a copy of the class?

I dont think ive personally actually gotten this idea to work. It sounds like a sensible idea especially for execution on a CI server somewhere.

However my approach has been to try and execute the majority of tests inside a real jvm (because its faster) and then write a separate HTML runner test that attempts to "verify" stuff got translated correctly and verify random APIs work, simply because when you have lots of tests JRE is much faster than JS. Ive always separated the HTML runners into a it-test and run them occassionally because they are slower and when doing iterative work they are too slow to run ever time theres a change.

Not sure why surefire isnt finding this test, could it be because it has `org.junit.Test` annotations and it is using the "wrong" runner ?

If you solve/dont solve this feel free to write up a PR, either way it will save time for others trying to do the same.

> I expect to make some contributions to this plugin and related packages as I get more familiar with them. Thanks for your work so far.

Thanx,
If you have any ideas, suggestions, contributions chat: Join https://gitter.im/gwtproject/gwt https://gitter.im/vertispan/j2cl

**Comment by mP1** [comment]
Another TODO in my head is to have junit4 support particulary regarding asserts (messages now are the last param) for consistency.

**Comment by mP1** [comment]
+1

**Comment by mP1** [comment]
> I think JavaIoTestJ2cl only actually works in surefire it doesnt get translated etc, the @J2clTestInput(JavaIoTestJ2cl.class) is a mistake/misleading.

My mistake it always gets translated and tested via HtmlRunner
